spring.application.name=SpringBootProj03-HealthSync

server.servlet.context-path=/healthsync

#DataBase credentials
spring.datasource.url=jdbc:mysql://localhost:3306/healthsync
spring.datasource.username=root
spring.datasource.password=manager
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=siddhantdaimsr2023@gmail.com
spring.mail.password=qagd rrvy ymyj rrsu

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#JWT
jwt.secret=aRNF5lmRDxWsE1yPBZxGRDzVV+ZmLrKAPvUOYw1Sfcg=